version: '3'
services:
  web:
    restart: always
    build: 
       context: .
       dockerfile: dockerfile
    #image: giabmf11/php72-upgrade
    volumes:
      - "~/[MAGENTO_REPO_LOCATION]:/var/www/magento2"
      - "~/.gitconfig:/home/magento2/.gitconfig"
      - "~/.composer:/home/magento2/.composer"
      - "~/.ssh:/home/magento2/.ssh"
      - "./shared/logs/apache2:/var/log/apache2"
      - "./shared/logs/php-fpm:/var/log/php-fpm"
      - "./shared/configs/varnish:/home/magento2/configs/varnish"
      - "./shared/.magento-cloud:/home/magento2/.magento-cloud"
    environment:
      - MAGENTO_BACKEND_PATH=admin
      - MAGENTO_ADMIN_USER=admin
      - MAGENTO_ADMIN_PASSWORD=admin123
    ports:
      - "80"
      - "22"
  db:
    restart: always
    image: mysql:5.6
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento2
    volumes:
      - "./shared/var/logs/mysql:/var/log/mysql"

  elasticsearch:
      image: elasticsearch:2
      ports:
        - "9200"
      volumes:
      - "./shared/esdata:/usr/share/elasticsearch/data"
